[package]
authors = ["sharks <sharks@sharks>"]
edition = "2018"
name = "deku"
version = "0.1.0"

[workspace]
members = [
    "deku-derive"
]

[dependencies]
deku_derive = { path = "deku-derive" }
nom = "5.0"
bitvec = "*"


[dev-dependencies]
hex-literal = "0.2"
rstest = "0.6"
